apiVersion: v1
kind: Service
metadata:
  name: roadsai
  labels:
    app: roadsai
spec:
  selector:
    app: roadsai
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
